config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'recipes#index'

  resources :recipes, only: %i[index show]
  namespace :api do
    namespace :v1 do
      resources :recipes, only: %i[index show]
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
# frozen_string_literal: true

class Recipe < ApplicationRecord
  validates_uniqueness_of :ingredients
  validates_presence_of :ingredients, :image

  paginates_per 10
end

app/controllers/api/v1/recipes_controller.rb
# frozen_string_literal: true

class Api::V1::RecipesController < ApplicationController
  skip_before_action :verify_authenticity_token
  
  def index
    search_recipes = Recipes::Search.new(recipes_params)    

    render json: { recipes: search_recipes.call, most_common_tags: search_recipes.most_common_tags, filter: recipes_params[:filter] }
  end

  def show
    recipe = Recipe.find params[:id]

    render json: { recipe: recipe }
  end

  private

  def recipes_params
    params.permit(:terms, :filter, :page)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
# frozen_string_literal: true

class RecipesController < ApplicationController
  def index
    search_recipes = Recipes::Search.new(recipes_params)
    @recipes = search_recipes.call
    @most_common_tags = search_recipes.most_common_tags
    @filter = recipes_params[:filter]
  end

  def show
    @recipe = Recipe.find params[:id]
  end

  private

  def recipes_params
    params.permit(:terms, :filter, :page)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def recipe_words(words)
    words.join(', ')
  end

  def search_filters
    %w[Ingredients Tags Name]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ucook app</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <!-- BOOTSTRAP 5-->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  <body>
    <div class="container">
      <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
          <%= link_to 'Ucook app', root_path, class: 'navbar-brand' %>
        </div>
      </nav>
      <div class="row">
        <div class="col">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/recipes/index.html.erb
<div class="row">
  <div class="col-4">
    <div class="row">
      <div class="col">
        <div class="mb-3 mt-5">
          <%= form_tag(recipes_path, method: :get) do %>
            <%= label_tag :filter, 'Filter Field', class: 'form-label' %>
            <%= select_tag :filter, options_for_select(search_filters, selected: @filter), class: 'form-select mb-3', autofocus: true %>
            <%= label_tag :terms, 'Search Field', class: 'form-label' %>
            <%= text_field_tag :terms, {}, class: 'form-control mb-3', placeholder: 'Type something here...' %>
            <%= submit_tag 'Bring me dishes', class: 'btn btn-primary mb-3' %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <div class="mb-3 mt-5">
          <h5>Most Common Tags</h5>
          <ul class="list-group list-group-flush">
            <% @most_common_tags.each do |k, v| %>
              <li class="list-group-item"><span class="badge bg-danger"><%= "#{k} - #{v}" %></span></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="col-8">
    <div class="row">
      <div class="col d-flex justify-content-center">
        <div class="mb-3 mt-5">
        <% unless @recipes.class == Array %>
          <%= paginate @recipes %>
        <% end %>
        </div>
      </div>
    </div>
    <% @recipes.each do |recipe| %>
      <div class="row">
        <div class="col">
          <div class="card mb-3">
            <div class="row">
              <div class="col-4">
                <img src="<%= recipe.image %>" class="img-fluid rounded-start" alt="">
              </div>
              <div class="col-8">
                <div class="card-body">
                  <h5 class="card-title">
                    <%= link_to recipe.name, recipe_path(id: recipe.id) %>
                    <span class="badge bg-warning text-dark"><%= recipe.rate %></span>
                  </h5>
                  <p class="card-text"><%= recipe_words(recipe.tags) %></p>
                  <p class="card-text"><small class="text-muted">Ready to eat in: <%= recipe.total_time %></small></p>
                </div>
              </div>
            </div>
          </div>
        </div> 
      </div>
    <% end %>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="row">
  <div class="col-8 offset-2 mb-3 mt-5">
    <div class="card bg-dark text-white">
      <img src="<%= @recipe.image %>" class="card-img" alt="">
      <div class="card-img-overlay">
        <h1 class="card-title"><%= @recipe.name %></h1>
        <h3 class="card-text"><%= recipe_words(@recipe.tags) %></h3>
        <p class="card-text">Ready to eat in: <%= @recipe.total_time %></p>
      </div>
    </div>
    </div>
</div>

<div class="row">
  <div class="col mb-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item"><strong><%= @recipe.name %></strong></li>
      <li class="list-group-item"><%= recipe_words(@recipe.tags) %></li>
      <li class="list-group-item"><%= recipe_words(@recipe.ingredients) %></li>
      <li class="list-group-item"><strong>Is it expensive? </strong><%= @recipe.budget %></li>
      <li class="list-group-item"><strong>Is it hard? </strong><%= @recipe.difficulty %></li>
      <li class="list-group-item"><strong>Food for </strong><%= @recipe.people_quantity %></li>
      <li class="list-group-item"><strong>Rated as </strong><%= @recipe.rate %></li>
      <li class="list-group-item"><strong>Thanks to </strong><%= @recipe.author %></li>
    </ul>
    </div>
</div>